/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Documentation for Clients",
  "description": "documentation for peterteszary.com clients",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-226bfdc6",
      "path": "/config/"
    },
    {
      "title": "Docs",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/docs/",
      "relativePath": "docs/README.md",
      "key": "v-4b2efca6",
      "path": "/docs/"
    },
    {
      "title": "This is the first document",
      "frontmatter": {},
      "regularPath": "/docs/doc-1.html",
      "relativePath": "docs/doc-1.md",
      "key": "v-7d77b561",
      "path": "/docs/doc-1.html"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-13885f08",
      "path": "/guide/"
    },
    {
      "title": "This is the Second document",
      "frontmatter": {},
      "regularPath": "/docs/Doc-2.html",
      "relativePath": "docs/Doc-2.md",
      "key": "v-5d6e649f",
      "path": "/docs/Doc-2.html"
    },
    {
      "title": "Main parts of WordPress",
      "frontmatter": {},
      "regularPath": "/guide/main-parts-of-wordpress.html",
      "relativePath": "guide/main-parts-of-wordpress.md",
      "key": "v-92ed7cb6",
      "path": "/guide/main-parts-of-wordpress.html",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://v1.vuepress.vuejs.org/hero.png",
        "tagline": "documentation for peterteszary.com clients",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "WordPress Documentation for Clients",
            "details": "Knowhow of WordPress for Clients"
          },
          {
            "title": "WooCommerce Documentation for Clients",
            "details": "The most common questions answered in this guide"
          },
          {
            "title": "Tips and Tricks for Clients",
            "details": "Small tips for everyday WordPress Users"
          }
        ],
        "footer": "Made by Peter Teszáry with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-a4a8e884",
      "path": "/"
    },
    {
      "title": "WordPress Admin login",
      "frontmatter": {},
      "regularPath": "/guide/wordpress-admin-login.html",
      "relativePath": "guide/wordpress-admin-login.md",
      "key": "v-38f76076",
      "path": "/guide/wordpress-admin-login.html",
      "headers": [
        {
          "level": 2,
          "title": "How To login to your WordPress Website",
          "slug": "how-to-login-to-your-wordpress-website"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "nav": [
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "Config",
        "link": "/config/"
      },
      {
        "text": "Documentation",
        "link": "/docs/"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "Guide",
          "collapsable": false,
          "children": [
            "",
            "main-parts-of-wordpress",
            "wordpress-admin-login"
          ]
        }
      ]
    }
  }
}